ALTER TABLE apps ADD COLUMN IF NOT EXISTS container_port VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN IF NOT EXISTS publish_port VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN IF NOT EXISTS container_name VARCHAR(255) NOT NULL DEFAULT '';