ALTER TABLE app_files ADD COLUMN file_type VARCHAR(16) NOT NULL DEFAULT 'text';
ALTER TABLE app_files ADD COLUMN file_size BIGINT NOT NULL DEFAULT 0;
ALTER TABLE app_files ADD COLUMN mime_type VARCHAR(256) NOT NULL DEFAULT '';