CREATE TABLE role_permissions (
    id SERIAL PRIMARY KEY,
    role VARCHAR(50) NOT NULL,
    permission VARCHAR(100) NOT NULL,
    UNIQUE(role, permission)
);

INSERT INTO role_permissions (role, permission) VALUES
    ('admin', 'users:read'),
    ('admin', 'users:write'),
    ('admin', 'users:delete'),
    ('admin', 'projects:read'),
    ('admin', 'projects:write'),
    ('admin', 'projects:delete'),
    ('admin', 'apps:read'),
    ('admin', 'apps:write'),
    ('admin', 'apps:delete'),
    ('admin', 'apps:deploy'),
    ('admin', 'configs:read'),
    ('admin', 'configs:write'),
    ('admin', 'cloudflare:read'),
    ('admin', 'cloudflare:write'),
    ('admin', 'proxy:read'),
    ('admin', 'proxy:write'),
    ('operator', 'users:read'),
    ('operator', 'projects:read'),
    ('operator', 'projects:write'),
    ('operator', 'apps:read'),
    ('operator', 'apps:write'),
    ('operator', 'apps:deploy'),
    ('operator', 'configs:read'),
    ('operator', 'configs:write'),
    ('operator', 'cloudflare:read'),
    ('operator', 'cloudflare:write'),
    ('operator', 'proxy:read'),
    ('viewer', 'users:read'),
    ('viewer', 'projects:read'),
    ('viewer', 'apps:read'),
    ('viewer', 'configs:read'),
    ('viewer', 'cloudflare:read'),
    ('viewer', 'proxy:read');